heat_template_version: pike

description: >
  Support proxying logs to stdout for haproxy

resources:

  SyslogProxy:
    type: ./syslog-proxy.yaml

outputs:
  config_settings:
    description: Extra hieradata needed to log to stdout.
    value:
      tripleo::haproxy::haproxy_log_address: "/syslogproxy/log"
  docker_config:
    description: Extra containers needed for logging to stdout or a sidecar container.
    value:
      step_1:
        haproxy_log:
          map_merge:
            - {get_attr: [SyslogProxy, sidecar_container]}
            - volumes:
                - haproxy_sockets:/sockets
  volumes:
    description: The volumes needed to log to stdout or a sidecar container.
    value:
      - haproxy_sockets:/sockets
      - haproxy_sockets:/var/lib/haproxy/sockets
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value: null
