heat_template_version: 2016-04-08

description: >
  OpenStack Cinder Scheduler service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  CinderSchedulerLoggingSource:
    type: json
    description: Fluentd logging configuration for cinder-scheduler.
    default:
      tag: openstack.cinder.scheduler
      path: /var/log/cinder/cinder-scheduler.log

resources:

  CinderBase:
    type: ./cinder-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Cinder Scheduler role.
    value:
      service_name: cinder_scheduler
      logging_source: {get_param: CinderSchedulerLoggingSource}
      config_settings:
        map_merge:
          - get_attr: [CinderBase, role_data, config_settings]
          - cinder::scheduler::scheduler_driver: cinder.scheduler.filter_scheduler.FilterScheduler
      step_config: |
        include ::tripleo::profile::base::cinder::scheduler
