heat_template_version: 2016-04-08

description: >
  OpenStack Glance Registry service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  GlancePassword:
    description: The password for the glance service and db account, used by the glance services.
    type: string
    hidden: true
  GlanceWorkers:
    default: 0
    description: Number of workers for Glance service.
    type: number
  GlanceRegistryLoggingSource:
    type: json
    description: Fluentd logging configuration for glance-registry.
    default:
      tag: openstack.glance.registry
      path: /var/log/glance/registry.log

outputs:
  role_data:
    description: Role data for the Glance Registry role.
    value:
      service_name: glance_registry
      logging_source: {get_param: GlanceRegistryLoggingSource}
      config_settings:
        glance::registry::database_connection:
          list_join:
            - ''
            - - {get_param: [EndpointMap, MysqlInternal, protocol]}
              - '://glance:'
              - {get_param: GlancePassword}
              - '@'
              - {get_param: [EndpointMap, MysqlInternal, host]}
              - '/glance'
        glance::registry::keystone_password: {get_param: GlancePassword}
        glance::registry::keystone_tenant: 'service'
        glance::registry::pipeline: 'keystone'
        glance::registry::auth_uri: {get_param: [EndpointMap, KeystoneInternal, uri] }
        glance::registry::identity_uri: { get_param: [EndpointMap, KeystoneAdmin, uri_no_suffix] }
        glance::registry::debug: {get_param: Debug}
        glance::registry::workers: {get_param: GlanceWorkers}
        glance::db::mysql::user: glance
        glance::db::mysql::host: {get_param: [EndpointMap, MysqlInternal, host_nobrackets]}
        glance::db::mysql::dbname: glance
        glance::db::mysql::allowed_hosts:
          - '%'
          - "%{hiera('mysql_bind_host')}"
        glance::registry::db::database_db_max_retries: -1
        glance::registry::db::database_max_retries: -1

        tripleo.glance_registry.firewall_rules:
          '112 glance_registry':
            dport:
              - 9191
      step_config: |
        include ::tripleo::profile::base::glance::registry
