heat_template_version: 2016-04-08

description: >
  OpenStack Nova Vncproxy service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NovaVncProxyLoggingSource:
    type: json
    description: Fluentd logging configuration for nova-vncproxy.
    default:
      tag: openstack.nova.vncproxy
      path: /var/log/nova/nova-vncproxy.log

resources:
  NovaBase:
    type: ./nova-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Nova Vncproxy service.
    value:
      service_name: nova_vncproxy
      logging_source: {get_param: NovaVncProxyLoggingSource}
      config_settings:
        map_merge:
          - get_attr: [NovaBase, role_data, config_settings]
          - nova::vncproxy::enabled: true
      step_config: |
        include tripleo::profile::base::nova::vncproxy
