heat_template_version: rocky

description: >
  TripleO Firewall settings

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ManageFirewall:
    default: true
    description: Whether to manage IPtables rules.
    type: boolean
  PurgeFirewallRules:
    default: false
    description: Whether IPtables rules should be purged before setting up the new ones.
    type: boolean
  DefaultFirewallRules:
    type: json
    description: These firewall rules will be realized on all overcloud hosts
    default:
      tripleo.tripleo_firewall.firewall_rules:
        '003 accept ssh':
          dport: 22
          proto: 'tcp'


outputs:
  role_data:
    description: Role data for the TripleO firewall settings
    value:
      service_name: tripleo_firewall
      config_settings:
        map_merge:
          - tripleo::firewall::manage_firewall: {get_param: ManageFirewall}
            tripleo::firewall::purge_firewall_rules: {get_param: PurgeFirewallRules}
          - {get_param: DefaultFirewallRules}
      step_config: |
        include ::tripleo::firewall
      upgrade_tasks:
        - name: blank ipv6 rule before activating ipv6 firewall.
          when: step|int == 3
          shell: cat /etc/sysconfig/ip6tables > /etc/sysconfig/ip6tables.n-o-upgrade; cat</dev/null>/etc/sysconfig/ip6tables
          args:
            creates: /etc/sysconfig/ip6tables.n-o-upgrade
